const PAGES={
 dashboard:{title:'Dashboard',subtitle:'Choose the right specialist and begin.',profile:'assistant'},
 tech:{title:'Tech Support',subtitle:'Diagnose first. Change the system only after approval.',profile:'pcfix',number:1,accent:'#7289a5',intro:'Describe the problem, symptoms and when it started.',empty:'Diagnostics, proposed steps and approvals will appear here.',tabs:['Result','Activity']},
 web:{title:'Web Search & Scrape',subtitle:'Grounded research and source-traceable extraction.',profile:'donsetch-tinyfish',number:2,accent:'#4f9da6',intro:'State the question, target sites or URL, required fields and output.',empty:'Research results, citations and source-traced rows will appear here.',tabs:['Result','Sources','Activity']},
 image:{title:'Image Creator',subtitle:'Generate, preview, revise and export visual work.',profile:'image-creator',number:3,accent:'#d47a5f',intro:'Describe the image, audience, use, dimensions, style and required text.',empty:'Generated images, revisions and export controls will appear here.',tabs:['Preview','Result','Activity']},
 teach:{title:'Teach Me',subtitle:'Learn step by step and keep a record of progress.',profile:'teach-me',number:4,accent:'#68a67a',intro:'Name the subject, your current level and what you need to do with it.',empty:'Lesson notes, subject progress and mastery checks will appear here.',tabs:['Lesson','Progress','Activity']},
 grill:{title:'Grill Me',subtitle:'Pressure-test your thinking before it matters.',profile:'grill-me',number:5,accent:'#9a78b8',intro:'Describe the scenario, stakes, audience and desired intensity.',empty:'Challenges, evidence gaps and the saved report will appear here.',tabs:['Report','Result','Activity']},
 system:{title:'Advanced & System',subtitle:'Native Hermes access, runtime status and local product controls.'}
};
const STORE_KEY='hermes-five-choices-v1';
const defaultState={theme:'slate',splits:{},chats:{},outputs:{},activities:{},teachProgress:{subjects:[]},grillReports:[]};
let state=loadState();let connectedProfiles=new Set();let timers={};
function loadState(){try{return {...defaultState,...JSON.parse(localStorage.getItem(STORE_KEY)||'{}')}}catch{return structuredClone(defaultState)}}
function saveState(){localStorage.setItem(STORE_KEY,JSON.stringify(state))}
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(el._timer);el._timer=setTimeout(()=>el.classList.remove('show'),2400)}
function extractUrls(text){return [...new Set((String(text).match(/https?:\/\/[^\s)\]}>,"']+/g)||[]))]}
function mediaFrom(text){const local=String(text).match(/MEDIA:\s*([^\r\n]+)/i);const remote=String(text).match(/!\[[^\]]*\]\((https?:\/\/[^)]+)\)/i);return remote?.[1]||local?.[1]?.trim()||''}
function chatHistory(id){return state.chats[id]||(state.chats[id]=[])}
function activityHistory(id){return state.activities[id]||(state.activities[id]=[])}
function addActivity(id,label,status='active',detail=''){const row={at:new Date().toISOString(),label,status,detail};activityHistory(id).push(row);if(activityHistory(id).length>40)activityHistory(id).splice(0,activityHistory(id).length-40);saveState();renderActivity(id);return row}
function elapsedLabel(start){const seconds=Math.max(0,Math.round((performance.now()-start)/1000));return seconds<60?`${seconds}s`:`${Math.floor(seconds/60)}m ${seconds%60}s`}
function createWorkspaces(){const host=document.getElementById('workspacePages');host.innerHTML=['tech','web','image','teach','grill'].map(id=>{const p=PAGES[id];return `<section class="page" id="page-${id}" style="--page-accent:${p.accent}"><div class="workspace-head"><div><div class="eyebrow">Choice ${p.number}</div><h2>${p.title}</h2><p>${p.intro}</p></div><span class="connection-chip" data-profile-state="${p.profile}">Checking…</span></div><div class="split-shell" data-split="${id}" style="--split:${state.splits[id]||'48%'}"><section class="pane input-pane"><div class="chat-log" data-log="${id}"></div><form class="composer" data-chat-form="${id}"><textarea data-input="${id}" rows="2" placeholder="Ask ${p.title}…"></textarea><button type="submit" class="primary">Send</button></form></section><div class="resizer" role="separator" tabindex="0" aria-label="Resize ${p.title} panes" aria-orientation="vertical" data-resizer="${id}"></div><section class="pane output-pane"><div class="pane-tabs">${p.tabs.map((tab,i)=>`<button class="pane-tab ${i===0?'active':''}" data-tab="${id}:${tab.toLowerCase()}">${tab}</button>`).join('')}</div><div class="output-body" data-output="${id}"></div></section></div></section>`}).join('');
 for(const id of ['tech','web','image','teach','grill']){renderChat(id);renderOutput(id);renderActivity(id)}
}
function createChoiceGrid(){document.getElementById('choiceGrid').innerHTML=['tech','web','image','teach','grill'].map(id=>{const p=PAGES[id];return `<button class="choice-card" data-page="${id}"><span class="choice-number">${p.number}</span><b>${p.title}</b><small>${p.subtitle}</small></button>`}).join('')}
function renderChat(id){const log=document.querySelector(`[data-log="${id}"]`);if(!log)return;const history=chatHistory(id);if(!history.length){const p=PAGES[id];log.innerHTML=`<div class="message assistant"><div class="message-meta">${esc(p.title)}</div><div>${esc(p.intro||'How can I help?')}</div></div>`;return}log.innerHTML=history.map(m=>`<div class="message ${m.role==='user'?'user':m.error?'assistant error':'assistant'}"><div class="message-meta">${m.role==='user'?'You':esc(PAGES[id].title)}${m.elapsed?` · ${esc(m.elapsed)}`:''}</div><div>${esc(m.content)}</div></div>`).join('');log.scrollTop=log.scrollHeight}
function renderActivity(id){const body=document.querySelector(`[data-output="${id}"]`);if(!body||body.dataset.view!=='activity')return;const rows=activityHistory(id);body.innerHTML=rows.length?`<div class="activity-list">${[...rows].reverse().map(r=>`<div class="activity-row ${esc(r.status)}"><span class="dot"></span><div><b>${esc(r.label)}</b>${r.detail?`<small>${esc(r.detail)}</small>`:''}</div><span class="activity-time">${new Date(r.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span></div>`).join('')}</div>`:`<div class="empty-output"><div><div class="symbol">◎</div><p>No activity recorded yet.</p></div></div>`}
function outputHtml(id){const p=PAGES[id],text=state.outputs[id]||'',urls=extractUrls(text),media=mediaFrom(text);if(!text)return `<div class="empty-output"><div><div class="symbol">${id==='image'?'▧':'◇'}</div><h3>Ready for output</h3><p>${esc(p.empty)}</p></div></div>`;if(id==='web')return `<div class="result-content">${esc(text)}</div>${urls.length?`<h3>Sources</h3><div class="source-list">${urls.map(u=>`<a class="source-link" href="${esc(u)}" target="_blank" rel="noopener">${esc(u)}</a>`).join('')}</div>`:''}`;if(id==='image')return `${media&&/^https?:/.test(media)?`<img class="image-preview" src="${esc(media)}" alt="Generated image preview">`:''}<div class="output-actions"><button class="ghost" data-export="png">Export PNG</button><button class="ghost" data-export="jpeg">Export JPEG</button><button class="ghost" data-export="webp">Export WebP</button></div><div class="result-content">${esc(text)}</div>`;if(id==='teach')return `<div class="progress-box"><b>Learning record</b><p>${state.teachProgress.subjects.length?esc(state.teachProgress.subjects.join(' · ')):'A subject is recorded after the first completed lesson.'}</p></div><div class="result-content">${esc(text)}</div>`;if(id==='grill')return `<div class="output-actions"><button class="primary" data-save-report>Save challenge report</button></div><div class="report-box"><div class="result-content">${esc(text)}</div></div>`;return `<div class="result-content">${esc(text)}</div>`}
function renderOutput(id){const body=document.querySelector(`[data-output="${id}"]`);if(!body)return;const view=body.dataset.view||PAGES[id].tabs[0].toLowerCase();body.dataset.view=view;if(view==='activity'){renderActivity(id);return}if(view==='sources'){const urls=extractUrls(state.outputs[id]||'');body.innerHTML=urls.length?`<div class="source-list">${urls.map(u=>`<a class="source-link" href="${esc(u)}" target="_blank" rel="noopener">${esc(u)}</a>`).join('')}</div>`:`<div class="empty-output"><p>No sources recorded yet.</p></div>`;return}if(view==='progress'){body.innerHTML=`<div class="progress-box"><h3>Subjects and mastery</h3><p>${state.teachProgress.subjects.length?esc(state.teachProgress.subjects.join(' · ')):'No subject recorded yet.'}</p></div>`;return}body.innerHTML=outputHtml(id)}
function showPage(id){if(!PAGES[id])return;document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${id}`));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===id));document.getElementById('pageTitle').textContent=PAGES[id].title;document.getElementById('pageSubtitle').textContent=PAGES[id].subtitle;history.replaceState(null,'',`#${id}`);if(id==='system')loadHealth()}
async function callProfileStream(profile,message,channel,onEvent){const response=await fetch('/api/chat/stream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile,message,mode:'resume',channel})});if(!response.ok){let data={};try{data=await response.json()}catch{}throw new Error(data.error||`Chat failed (${response.status})`)}if(!response.body)throw new Error('Streaming unavailable');const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',answer='',meta={};const dispatch=block=>{let event='message',lines=[];for(const line of block.split('\n')){if(line.startsWith('event:'))event=line.slice(6).trim();else if(line.startsWith('data:'))lines.push(line.slice(5).trimStart())}if(!lines.length)return;let data={};try{data=JSON.parse(lines.join('\n'))}catch{return}if(event==='dashboard.meta')meta={...meta,...data};else if(event==='assistant.delta')answer+=data.delta||'';else if(event==='assistant.completed')answer=data.content||answer;else if(event==='error')throw new Error(data.message||'Hermes streaming error');onEvent({event,data,answer,meta})};while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done}).replace(/\r\n/g,'\n');let n;while((n=buffer.indexOf('\n\n'))>=0){const block=buffer.slice(0,n);buffer=buffer.slice(n+2);if(block&&!block.startsWith(':'))dispatch(block)}if(done)break}if(buffer.trim()&&!buffer.startsWith(':'))dispatch(buffer);if(!answer)throw new Error('Hermes returned no response');return answer}
async function submitChat(id){const form=document.querySelector(`[data-chat-form="${id}"]`),input=document.querySelector(`[data-input="${id}"]`),button=form?.querySelector('button[type=submit]'),message=input?.value.trim(),p=PAGES[id];if(!message||!p?.profile||button?.disabled)return;chatHistory(id).push({role:'user',content:message});chatHistory(id).push({role:'assistant',content:'Connecting…',pending:true});input.value='';button.disabled=true;renderChat(id);const start=performance.now();addActivity(id,'Request received','active',message.slice(0,100));timers[id]=setInterval(()=>{const row=activityHistory(id).at(-1);if(row&&row.status==='active'){row.detail=`Working · ${elapsedLabel(start)}`;renderActivity(id)}},1000);try{const answer=await callProfileStream(p.profile,message,id,({event,data,answer})=>{const current=chatHistory(id).at(-1);if(event==='dashboard.meta'){current.content='Connected to Hermes…';addActivity(id,'Connected to specialist','active',p.profile)}else if(event==='assistant.delta'){current.content=answer;renderChat(id)}else if(event==='tool.started'||event==='tool.progress'){addActivity(id,`Tool active: ${data.name||data.tool||data.message||'Hermes tool'}`,'active')}else if(event==='tool.completed'){addActivity(id,`Tool completed: ${data.name||data.tool||'Hermes tool'}`,'done')}else if(event==='tool.failed'){addActivity(id,`Tool failed: ${data.name||data.tool||'Hermes tool'}`,'error',data.error||'')}else if(event==='run.started'){addActivity(id,'Hermes run started','active')}else if(event==='run.completed'){addActivity(id,'Hermes run completed','done')}});const current=chatHistory(id).at(-1);current.content=answer;current.pending=false;current.elapsed=elapsedLabel(start);state.outputs[id]=answer;if(id==='teach'){const subject=message.split(/[?.!]/)[0].slice(0,70);if(subject&&!state.teachProgress.subjects.includes(subject))state.teachProgress.subjects.push(subject)}addActivity(id,'Completed','done',current.elapsed);saveState();renderChat(id);renderOutput(id)}catch(error){const current=chatHistory(id).at(-1);current.content=error.message;current.pending=false;current.error=true;addActivity(id,'Request failed','error',error.message);saveState();renderChat(id);renderOutput(id)}finally{clearInterval(timers[id]);button.disabled=false}}
function setupResizers(){document.querySelectorAll('[data-resizer]').forEach(handle=>{const id=handle.dataset.resizer,shell=handle.closest('.split-shell');const set=x=>{const rect=shell.getBoundingClientRect(),pct=Math.min(67,Math.max(33,(x-rect.left)/rect.width*100));shell.style.setProperty('--split',`${pct}%`);state.splits[id]=`${pct}%`;saveState()};handle.addEventListener('pointerdown',event=>{handle.setPointerCapture(event.pointerId);const move=e=>set(e.clientX),up=e=>{handle.releasePointerCapture(e.pointerId);handle.removeEventListener('pointermove',move);handle.removeEventListener('pointerup',up)};handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',up)});handle.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight'].includes(event.key))return;event.preventDefault();const current=parseFloat(state.splits[id]||'48');const next=Math.min(67,Math.max(33,current+(event.key==='ArrowRight'?2:-2)));shell.style.setProperty('--split',`${next}%`);state.splits[id]=`${next}%`;saveState()})})}
function setupTabs(){document.addEventListener('click',event=>{const tab=event.target.closest('[data-tab]');if(!tab)return;const [id,view]=tab.dataset.tab.split(':');tab.parentElement.querySelectorAll('.pane-tab').forEach(b=>b.classList.toggle('active',b===tab));document.querySelector(`[data-output="${id}"]`).dataset.view=view;renderOutput(id)})}
async function loadHealth(){try{const [health,profiles]=await Promise.all([fetch('/api/health',{cache:'no-store'}).then(r=>r.json()),fetch('/api/profiles',{cache:'no-store'}).then(r=>r.json())]);if(!health.ok)throw new Error('Companion is not healthy');connectedProfiles=new Set(profiles.profiles.filter(p=>p.connected).map(p=>p.slug));document.getElementById('healthDot').className='status-dot good';document.getElementById('healthText').textContent='Hermes connected';document.querySelectorAll('[data-profile-state]').forEach(el=>{const ok=connectedProfiles.has(el.dataset.profileState);el.textContent=ok?'Connected':'Not configured';el.className=`connection-chip ${ok?'good':'bad'}`});document.getElementById('runtimeVersion').textContent=health.runtime_version||'0.20.6 candidate';document.getElementById('companionState').textContent='Healthy';document.getElementById('profileCount').textContent=`${connectedProfiles.size} of 6 connected`}catch(error){document.getElementById('healthDot').className='status-dot bad';document.getElementById('healthText').textContent='Hermes unavailable';document.querySelectorAll('[data-profile-state]').forEach(el=>{el.textContent='Offline';el.className='connection-chip bad'});const c=document.getElementById('companionState');if(c)c.textContent='Unavailable'}}
function setupEvents(){document.addEventListener('click',event=>{const page=event.target.closest('[data-page]');if(page)showPage(page.dataset.page);const exportButton=event.target.closest('[data-export]');if(exportButton)toast(`${exportButton.dataset.export.toUpperCase()} export activates when a generated image file is available.`);if(event.target.closest('[data-save-report]')){const text=state.outputs.grill||'';if(!text)return toast('No completed challenge report to save.');state.grillReports.push({savedAt:new Date().toISOString(),content:text});saveState();toast('Challenge report saved locally.')}});document.querySelectorAll('[data-chat-form]').forEach(form=>form.addEventListener('submit',event=>{event.preventDefault();submitChat(form.dataset.chatForm)}));document.querySelectorAll('textarea[data-input]').forEach(input=>input.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();submitChat(input.dataset.input)}}));document.querySelectorAll('[data-theme-choice]').forEach(button=>button.addEventListener('click',()=>applyTheme(button.dataset.themeChoice)));document.getElementById('openDesktop').addEventListener('click',async()=>{try{const r=await fetch('/api/system/open-desktop',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}),data=await r.json();if(!r.ok||!data.ok)throw new Error(data.error||'Unable to open Hermes Desktop');toast('Opening Hermes Desktop…')}catch(e){toast(e.message)}});document.getElementById('clearUiState').addEventListener('click',()=>{if(!confirm('Clear dashboard display state? Hermes profile sessions and generated files are not deleted.'))return;localStorage.removeItem(STORE_KEY);location.reload()})}
function applyTheme(theme){state.theme=theme;document.documentElement.dataset.theme=theme;document.querySelectorAll('[data-theme-choice]').forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===theme));saveState()}
function init(){createChoiceGrid();createWorkspaces();setupResizers();setupTabs();setupEvents();applyTheme(state.theme||'slate');renderChat('dashboard');showPage((location.hash||'#dashboard').slice(1) in PAGES?(location.hash||'#dashboard').slice(1):'dashboard');loadHealth()}
init();
